language: node_js
node_js:
  - "6"
os:
  - linux
  - windows
install:
  - npm update
  - npm install
script:
  - npm run lint
  - npm test
after_success:
  - codecov -f test/coverage/coverage-final.json
